[aria]
; edurom
; ip_address = 172.22.17.156 

; hotspot pc 
; ip_address = 10.42.0.68

; IP MODEM CASA 
ip_address = 192.168.1.3

;ip_address = 192.168.0.207
connection_type=wifi
update_iptables=true

[websocket]
host=0.0.0.0
port=8080

[streaming]
profile_name=profile26
streaming_interface=wifi
min_battery_level=20

[debug]
enabled=false
;video_path=/home/mick/projectaria_thesis/vrs_handler/402_5fps_video.mp4
video_path=/media/mick/MICK_BACKUP/auler/1602/1602_exit_video.mp4
; video_path=/home/mick/projectaria_thesis/vrs_handler/1602_R1_video.mp4
;video_path=/home/mick/projectaria_thesis/vrs_handler/1602_R4b_video.mp4
;video_path=/home/mick/projectaria_thesis/vrs_handler/1602_R1_2_video.mp4
; video_path = /media/mick/MICK_BACKUP/aria_rec/test1_video.mp4